version: '3'
services:
  mongo:
    image: mongo:4.0.3
    container_name: garcon-mongo
    env_file:
      - private/mongo.list
    ports:
      - "27019:27017"
    volumes:
      - mongo-volume:/data/db
    restart: on-failure:5

  main:
    image: garconzio/garconzio
    depends_on:
      - mongo
    build: target/docker
    container_name: garcon-main
    ports:
      - "5005:5005"
    volumes:
      - main-logs-volume:/logs
    restart: on-failure:5

volumes:
  mongo-volume:
  main-logs-volume: