name: Scala CI

on: [push]

jobs:
  tests:
    if: "!startswith(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 1.12
        uses: actions/setup-java@v1
        with:
          java-version: 1.12

      - name: Place secrets for integration testing
        shell: bash
        run: |
          [ ! -f test_api_keys.conf ]
          echo abbyy.testApiKey = "${{ secrets.abbyy_test_key }}" >> test_api_keys.conf
          echo yandex.testApiKey = "${{ secrets.yandex_test_key }}" >> test_api_keys.conf
          mkdir -p src/test/resources/private && cp test_api_keys.conf $_
          mkdir -p translator/src/test/resources/private && cp test_api_keys.conf $_

      - name: Run tests
        run: sbt test
